version: '3'

services:
  api:
    build: ecommerce_database/
    depends_on:
      - 'database'
    volumes:
      - './ecommerce_database:/src/app'
      - '/src/app/node_modules'

    ports: 
      - '3001:3001'

  database:
    build: postgresql/
    restart: always
    environment:
      POSTGRES_USER: jessicachen
      POSTGRES_PASSWORD: password